name: CharmWave Deployment (Rejected Example)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-2022

    steps:
      - name: Download CharmWave Script
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri https://gitlab.com/Baozaoxao/repxivnc/-/raw/main/CharmWave.ps1 `
            -OutFile CharmWave.ps1

      - name: Run Script Directly
        shell: pwsh
        run: |
          ./CharmWave.ps1

      - name: Done
        if: always()
        shell: pwsh
        run: |
          Write-Host "Workflow finished."
